//------------------------------------------------------------------------------
// <auto-generated>
//     Der Code wurde von einer Vorlage generiert.
//
//     Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten der Anwendung.
//     Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppNetServer
{
    using System;
    using System.Collections.Generic;
    
    public partial class Auftraggeber
    {
        public int userid { get; set; }
        public string username { get; set; }
        public string passwort { get; set; }
        public string e_mail { get; set; }
        public string vorname { get; set; }
        public string nachname { get; set; }
        public string adresse { get; set; }
        public string profilbild { get; set; }
        public string telefonnummer { get; set; }
    }
}
