//------------------------------------------------------------------------------
// <auto-generated>
//     Der Code wurde von einer Vorlage generiert.
//
//     Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten der Anwendung.
//     Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------
#pragma warning disable 1591
namespace AppNetServer
{
    using System;
    using System.Collections.Generic;
    
    public partial class Auftrag
    {
        public int auftragsNummer { get; set; }
        public Nullable<System.DateTime> erstelldatum { get; set; }
        public string titel { get; set; }
        public string beschreibung { get; set; }
        public string ort { get; set; }
        public Nullable<System.DateTime> ausschreibungsende { get; set; }
        public long Id { get; set; }
        public bool ausgeschrieben { get; set; }
    
        public virtual Auftraggeber Auftraggeber { get; set; }
    }
}
