//------------------------------------------------------------------------------
// <auto-generated>
//     Der Code wurde von einer Vorlage generiert.
//
//     Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten der Anwendung.
//     Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppNetServer
{
    using System;
    using System.Collections.Generic;
    
    public partial class Bewertung
    {
        public int wert { get; set; }
        public string kommentar { get; set; }
        public int auftragnehmerId { get; set; }
        public int auftraggeberId { get; set; }
        public int auftragsId { get; set; }
    }
}
