//------------------------------------------------------------------------------
// <auto-generated>
//     Der Code wurde von einer Vorlage generiert.
//
//     Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten der Anwendung.
//     Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------
#pragma warning disable 1591
namespace AppNetServer
{
    using System;
    using System.Collections.Generic;
    
    public partial class Offerte
    {
        public int offertenNummer { get; set; }
        public Nullable<int> kostenvoranschlag { get; set; }
        public byte[] erstelldatum { get; set; }
        public string status { get; set; }
    }
}
